### ISSUE TITLE
PLEASE READ! 🤞

### ISSUE THREAD

**Issue by Fibbitts** [Armin2208/Windows-Auto-Night-Mode#194] opened 2020-12-19 23:51 UTC
Hey there! I absolutely love this app, and how you understand how apps such as Office don't support auto dark mode, and how you implemented that. The problem is that everyone has different software. I wrote a separate CMD that modifies config files and registry entries to set my other dark mode apps. But now I just need to schedule it! I tried Task Scheduler, but the problem is that I get on the computer at different times, and the only way to make it run is to run it EVERY HOUR. This gets a bit annoying, since it always pops up all the time setting my apps to dark/light mode, because I'll never know when I get on. I would _really_appriciate it if you allowed a custom script to run _after_ dark mode was activated, it would make my day. 👏♥ I've noticed a few other people have asked this as well. I am sure it would not take super long, and the community would very much appreciate it.

                 -And if you do decide to implement this, pop me a message at tech_how_youtuber55@yahoo.com

Thanks so much for reading!

**Comment by Armin2208** [comment] 2020-12-20 16:37
this will be implemented, duplicate of #186

**Closed by Armin2208** 2020-12-20 16:37 UTC
