### ISSUE TITLE
So many problems with the new update

### ISSUE THREAD

**Issue by androidmessages** [Armin2208/Windows-Auto-Night-Mode#43] opened 2019-06-23 18:46 UTC
Unfortunately, the new update has brought more bad than good.

1. Instant theme switching is gone. It isn't as bad as before, but I can wait a solid two or three minutes before the switch happens. Even after, it isn't proper. The taskbar color becomes grey when theme switches from dark to light, and I have to restart Windows Explorer to fix that.
2. Wallpaper changing gets disabled automatically. I tried uploading very small sized images hoping it'll fix the problem, but alas, to no avail.
3. Applying my settings produces "[an error occurred :(](https://ibin.co/4lcXC0EJxgra.jpg)".
4. When I try to move the Auto Dark Mode window, the movement isn't immediate. Rather, it's slow, delayed, and smooth. So I could've moved my the cursor already to the left, but on the screen, it'd take a smooth second or two for that to translate. See video [here](https://streamable.com/zsn2c).

 - OS Version: Windows 1903
 - Night-Mode Version [e.g. 2.2]
 - Has user admin rights? Yes
 - which antivirus software you use? Windows Defender
 - what language is your Windows set to? English

**Additional context**
I tried reinstalling, it didn't work.

**Comment by Armin2208** [comment] 2019-07-15 17:00
1. The theme should switch instant. While using Windows, after boot/restart and after hibernate, sleep and safe sleep. Do you use a mobile device? Try to deactivate energy saver, this causes some issues with theme switching.

2. Okay that's weird, I need to look into this, but I don't know how atm.

3. Please try the new Version 2.3 Beta. It has more detailed error messages. Send me a screenshot with it. Did you tried to uninstall Auto Dark Mode and then install it again?

4. Fixed in Version 2.3 Beta.

Thanks for your good issue.

**Comment by androidmessages** [comment] 2019-07-22 14:42
Thanks for your help! The new update has definitely fixed #2-4. I still wish the theme switching is faster, and that it doesn't glitch out the taskbar as it does occasionally. This esp. happens when I turn off my computer at night then turn it back on in the morning. It messes up with taskbar icon transparency, but after I move my cursor around a bit and do some clicking in and out, everything is fixed.

Also, as an aside, will you update Auto Dark Mode to include the new Chromium Edge in the near future?

**Comment by Armin2208** [comment] 2019-07-22 14:50
Does Auto Dark Mode switch instant after waking up your PC? Or you have only problems with your taskbar? You don't have an mobile device with energy saver activated?

Chromium Edge follows the system settings for all Apps, so no extra Edge-Option is needed this time :) Same with Firefox and Chrome.

**Comment by androidmessages** [comment] 2019-07-22 15:09
I do often have battery saver mode on for my laptop. Maybe that is what is messing up the switching time and causing the taskbar problems. I like the new error messages. I just downloaded the latest version you released yesterday, and I was prompted, "Due to a Windows bug the taskbar doesn't properly switch its colour in battery saver mode. Please turn off battery saver if you run into issues."

**Comment by Armin2208** [comment] 2019-07-22 16:22
The problem is its a windows bug. Really.
Even if you switch in windows settings the theme you see the Taskbar glitch. Sadly.

We need to wait for a fix of Microsoft.

**Closed** 2019-10-22 06:18 UTC
Labels: help wanted
