### ISSUE TITLE
Visual Studio Code does not switch back to light theme

### ISSUE THREAD

**Issue by KKire** [Armin2208/Windows-Auto-Night-Mode#154] opened 2020-08-05 13:22 UTC
**Describe the bug**
When using Auto Night Mode and VS Code is set to also change theme depending on system, when auto night mode switches to dark mode, VS Code switches too, but when ANM switches to light mode, VS Code doesn't. I have tried swithing manually from Settings and works but doesn't when ANM switches from dark to light.

**To Reproduce**
1. Set Auto Night Mode to switches theme
2. Set Visual Studio Code to switch theme based on system (window.autoDetectColorScheme)
3. ANM switches to dark mode, VS Code switches to dark mode (workbench.preferredDarkColorTheme)
4. ANM switches to light mode, VS Code does not switch

**Expected behavior**
Visual Studio Code should switch to light theme based on setting (workbench.preferredLightColorTheme)

**Environment:**
 - Auto Dark Mode version number: 3.0
 - OS Version: Windows 2004
 - OS language: Macedonian - North Macedonia [mk-MK]
 - Has user admin rights? - Yes
 - AntiVirus software: None (Defender)

**Comment by JensMertelmeyer** [comment] 2020-10-07 09:22
Cannot reproduce with 

- Auto Dark Mode 3.0.1
- Visual Studio Code 1.49.3
- Windows 20H2

It works flawlessly.

**Comment by KKire** [comment] 2020-10-07 09:30
I noticed too that this no longer happens. Probably it was fixed with VS Code updates.

**Comment by JensMertelmeyer** [comment] 2020-10-08 08:26
You might want to close this issue, then 😉

**Closed** 2020-10-08 08:34 UTC
