### ISSUE TITLE
Would the desktop background changer support slideshow mode?

### ISSUE THREAD

**Issue by zhangz22** [Armin2208/Windows-Auto-Night-Mode#58] opened 2019-10-22 03:09 UTC
Thanks for this great software. I wonder if the desktop wallpaper changer in this app would support the slideshow (switching wallpapers automatically in a folder) in the future?

**Comment by Armin2208** [comment] 2019-10-22 21:06
Duplicate of #35

**Closed by Armin2208** 2019-10-22 21:06 UTC
