### ISSUE TITLE
when  it work Windows taskbar icon Display is not normal

### ISSUE THREAD

**Issue by cwoesj** [Armin2208/Windows-Auto-Night-Mode#66] opened 2019-11-23 02:14 UTC
when  it switch the mode , Windows taskbar icon Display is not normal,some in black mode some in white mode(such as battery icon in dark mode Network icon in white mode) its looks uncomfortable
can you fix it? maybe just me have this bug?

**Comment by Armin2208** [comment] 2019-11-23 07:29
When you're notebook is in battery saver mode, the switch doesn't work properly.

**Comment by cwoesj** [comment] 2019-11-23 09:21
NO    Iam   sure   I am  not  in  battery save  mode

发件人: Armin Osaj
发送时间: Saturday, November 23, 2019 3:30 PM
收件人: Armin2208/Windows-Auto-Night-Mode
抄送: Chen-cwoest; Author
主题: Re: [Armin2208/Windows-Auto-Night-Mode] when it work Windows taskbaricon Display is not normal (#66)

When you're notebook is in battery saver mode, the switch doesn't work properly.

**Comment by Armin2208** [comment] 2019-11-23 10:28
can you send a screenshot?

**Comment by cwoesj** [comment] 2019-11-25 01:19
It`s a small problem just like that pictures  When I reatart the windows exploer it had gone Thank you for the reply
 I `m sorry to disturb I just a little OCD
发件人: Armin Osaj
发送时间: Saturday, November 23, 2019 6:28 PM
收件人: Armin2208/Windows-Auto-Night-Mode
抄送: Chen-cwoest; Author
主题: Re: [Armin2208/Windows-Auto-Night-Mode] when it work Windows taskbaricon Display is not normal (#66)

can you send a screenshot?

**Comment by Spiritreader** [comment] 2020-02-12 14:17
possible duplicate of #76

**Comment by Armin2208** [comment] 2020-04-20 08:22
Do you use Accent Color for Taskbar?

**Comment by cwoesj** [comment] 2020-04-23 12:21
Thank you for your reply ,Do you mean this Like the picture select?  In actually this is a small trouble, There is a certain probability of his appearance and now I ignore it.

**Comment by Spiritreader** [comment] 2020-07-09 18:14
Fix is implemented in version 3 and up.
Please see #91 for further details.

**Closed by Spiritreader** 2020-07-09 18:14 UTC
Labels: bug, help wanted
