### ISSUE TITLE
Feature Request: System tray icon

### ISSUE THREAD

**Issue by fredddd1** [Armin2208/Windows-Auto-Night-Mode#220] opened 2021-03-23 08:42 UTC
As I understand this program is running all the time in the background. For software that does this I would like to know they are running, by having an icon in the system tray and preferably with an Exit option if I right click it.

**Comment by emberaholdon** [comment] 2021-03-23 09:06
> As I understand this program is running all the time in the background.

It does not. It uses the Windows Task Scheduler to kick in then exits. The app you launch to configure the settings is just creating the scheduled tasks.

**Comment by emberaholdon** [comment] 2021-03-23 23:58
> Will this app run at all, ever, to check for updates? Or will it only do so when I open it myself?

You'll have to wait for an exact answer from Armin, but the app says:
![image](https://user-images.githubusercontent.com/67831954/112233962-b4d8d380-8c3b-11eb-87d5-c4fa6303a4cd.png)
so I'd imagine that every time the app is run by the scheduler it also checks for updates.

The app wasn't updated since I started using it so we'll have to wait and see.

**Comment by Armin2208** [comment] 2021-03-24 23:58
yep, the app never runs in background. It just triggers a scheduled task. 
One for dark theme, one for light theme, one for startup, one for software update checks, one for location update checks / updating sunset and sunrise times.

we already have implemented a real tray icon in taskbar in an beta build we didn't shared yet on github.
![image](https://user-images.githubusercontent.com/32982430/112398783-2cbf0080-8d05-11eb-8ee9-7d5edcf908c5.png)

btw closed because duplicate of #26

**Closed by Armin2208** 2021-03-24 23:58 UTC

**Comment by emberaholdon** [comment] 2021-03-25 00:09
> we already have implemented a real tray icon in taskbar in an beta build we didn't shared yet on github.

Just please make it optional. I hate systray icons. 😀

**Comment by Armin2208** [comment] 2021-03-25 00:45
> > we already have implemented a real tray icon in taskbar in an beta build we didn't shared yet on github.
> 
> Just please make it optional. I hate systray icons. 😀

yep, because someone here on GitHub or on Telegram I will implement an option to deactivate the system tray :D 
It's not necessary anyways, because the jump list will still be there :)
